# Generated by Django 2.2.14 on 2020-08-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometeam', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('awayteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Team')),
            ],
        ),
    ]
