# Generated by Django 2.2.14 on 2020-09-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200805_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='owner',
            name='tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
