# Generated by Django 2.2.14 on 2020-09-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200919_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Schedule')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Person')),
            ],
        ),
    ]
