# Generated by Django 2.2.14 on 2020-09-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='person',
            field=models.IntegerField(),
        ),
    ]
