# Generated by Django 2.2.14 on 2020-09-29 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20200929_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Person'),
        ),
    ]
