# Generated by Django 2.2.14 on 2020-09-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20200929_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Req',
            new_name='Requirement',
        ),
    ]
