# Generated by Django 2.2.14 on 2020-09-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20200929_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='req',
            new_name='requirement',
        ),
    ]
