# Generated by Django 2.2.14 on 2020-09-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20200929_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirement',
            new_name='Req',
        ),
        migrations.RenameField(
            model_name='req',
            old_name='requirement',
            new_name='req',
        ),
    ]
