# Generated by Django 2.2.14 on 2020-10-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20200929_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenBest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberTickets', models.IntegerField()),
                ('TenBestNumber', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Schedule')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DuplicateTeams', models.IntegerField()),
                ('BackToBack', models.IntegerField()),
                ('AverageRating', models.DecimalField(decimal_places=5, max_digits=7)),
                ('TenBestNumber', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Person')),
            ],
        ),
        migrations.CreateModel(
            name='BestTen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.DecimalField(decimal_places=5, max_digits=7)),
                ('bads', models.IntegerField()),
                ('TenBestNumber', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Owner')),
            ],
        ),
    ]
