# Generated by Django 2.2.14 on 2020-10-13 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_bestten_status_tenbest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causenfo', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Owner')),
            ],
        ),
    ]
