# Generated by Django 2.2.14 on 2020-10-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_noresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noresult',
            old_name='causenfo',
            new_name='causeinfo',
        ),
    ]
