# Generated by Django 2.2.14 on 2020-10-15 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20201013_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Team'),
        ),
    ]
