# Generated by Django 2.2.14 on 2021-02-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20201014_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lastyear',
            field=models.BooleanField(default=False),
        ),
    ]
