# Generated by Django 2.2.14 on 2021-03-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20210227_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
