# Generated by Django 2.2.14 on 2021-03-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_owner_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='startdate',
            field=models.DateField(default=None),
        ),
    ]
