# Generated by Django 2.2.14 on 2021-03-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20210315_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
