# Generated by Django 2.2.14 on 2021-03-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_auto_20210315_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='startdate',
        ),
    ]
